Attribute VB_Name = "EXPCNCAPSUBS"
'******************************************************************************************
'***** VB Compress Pro 6.11.32 generated this copy of EXPCNCAP.BAS on Wed 6/17/09 @ 12:56 P
'***** Mode: AutoSelect Standard Mode (Internal References Only)***************************
'******************************************************************************************

' Copyright 1993 Counterpoint Software, Inc. All rights reserved.
' Proprietary Software, Do not copy
'
' File Name: ExpCnCAP.Bas
'
' Release: 1.0
'
' Description:
'   This file contains the Export Selling to Airing Links subs and functions
Option Explicit
Option Compare Text
Public lgCntrCode() As Long
'Public igShowHelpMsg As Integer
