'******************************************************************************************
'***** VB Compress Pro 6.11.32 generated this copy of VBTRVERR.BAS on Wed 6/17/09 @ 12:56 P
'***** Mode: AutoSelect Standard Mode (Internal References Only)***************************
'******************************************************************************************

' Copyright 1992, 1993 Classic Software, Inc. All rights reserved.
' Btrieve is a registered trademark of Novell, Inc.
'
' File Name: VBTRVERR.TXT
'
' Release: 2.0
'
' Description:
'   This file contains the constant definitions for all the status codes returned by
'   Btrieve.

Global Const BTRV_ERR_NONE             = 0
Global Const BTRV_ERR_INVALID_OP       = 1
Global Const BTRV_ERR_IO_ERR           = 2
Global Const BTRV_ERR_NOT_OPEN         = 3
Global Const BTRV_ERR_KEY_NOT_FOUND    = 4
Global Const BTRV_ERR_DUPLICATE_KEY    = 5
Global Const BTRV_ERR_INVALID_KEY      = 6
Global Const BTRV_ERR_DIFF_KEY         = 7
Global Const BTRV_ERR_INVALID_POS      = 8
Global Const BTRV_ERR_END_OF_FILE      = 9
Global Const BTRV_ERR_MOD_KEY_VALUE    = 10
Global Const BTRV_ERR_INVALID_FNAME    = 11
Global Const BTRV_ERR_FILE_NOT_FOUND   = 12
Global Const BTRV_ERR_EXT_FILE         = 13
Global Const BTRV_ERR_PREIMAGE_OPEN    = 14
Global Const BTRV_ERR_PREIMAGE_IO      = 15
Global Const BTRV_ERR_EXPANSION        = 16
Global Const BTRV_ERR_CLOSE            = 17
Global Const BTRV_ERR_DISK_FULL        = 18
Global Const BTRV_ERR_UNRECOVERABLE    = 19
Global Const BTRV_ERR_MGR_INACTIVE     = 20
Global Const BTRV_ERR_KEYBUF_LENGTH    = 21
Global Const BTRV_ERR_DATABUF_LENGTH   = 22
Global Const BTRV_ERR_POSBLK_LENGTH    = 23
Global Const BTRV_ERR_PAGESIZE         = 24
Global Const BTRV_ERR_CREATE_IO        = 25
Global Const BTRV_ERR_NUMKEYS          = 26
Global Const BTRV_ERR_INVALID_KEYPOS   = 27
Global Const BTRV_ERR_REC_LENGTH       = 28
Global Const BTRV_ERR_KEY_LENGTH       = 29
Global Const BTRV_ERR_NOT_BTRV_FILE    = 30
Global Const BTRV_ERR_ALREADY_EXTD     = 31
Global Const BTRV_ERR_EXTD_IO          = 32
Global Const BTRV_ERR_INVALID_EXT_NAME = 34
Global Const BTRV_ERR_DIRECTORY        = 35
Global Const BTRV_ERR_TRANSACTION      = 36
Global Const BTRV_ERR_TRANS_ACTIVE     = 37
Global Const BTRV_ERR_TRANS_FILE_IO    = 38
Global Const BTRV_ERR_END_ABORT_TRANS  = 39
Global Const BTRV_ERR_TRANS_MAX_FILES  = 40
Global Const BTRV_ERR_OP_NOT_ALLOWED   = 41
Global Const BTRV_ERR_ACCEL_ACCESS     = 42
Global Const BTRV_ERR_INVALID_REC_ADDR = 43
Global Const BTRV_ERR_NULL_KEY_PATH    = 44
Global Const BTRV_ERR_INCON_KEY_FLAGS  = 45
Global Const BTRV_ERR_ACCESS_DENIED    = 46
Global Const BTRV_ERR_MAX_OPEN_FILES   = 47
Global Const BTRV_ERR_INVALID_ALT_SEQ  = 48
Global Const BTRV_ERR_KEY_TYPE         = 49
Global Const BTRV_ERR_OWNER_SET        = 50
Global Const BTRV_ERR_INVALID_OWNER    = 51
Global Const BTRV_ERR_WRITE_CACHE      = 52
Global Const BTRV_ERR_INVALID_INTF     = 53
Global Const BTRV_ERR_VARIABLE_PAGE    = 54
Global Const BTRV_ERR_INCOMPLT_INDEX   = 56
Global Const BTRV_ERR_EXPAND_MEM       = 57
Global Const BTRV_ERR_COMPBUF_SIZE     = 58
Global Const BTRV_ERR_FILE_EXISTS      = 59
Global Const BTRV_ERR_REJECT_COUNT     = 60
Global Const BTRV_ERR_WORK_SPACE_SIZE  = 61
Global Const BTRV_ERR_INCORRECT_DESCP  = 62
Global Const BTRV_ERR_INVALID_EXTDBUF  = 63
Global Const BTRV_ERR_FILTER_LIMIT     = 64
Global Const BTRV_ERR_INCOR_FLD_OFFSET = 65
Global Const BTRV_ERR_AUTO_TRANS_ABORT = 74
Global Const BTRV_ERR_DEADLOCK_DETECT  = 78
Global Const BTRV_ERR_CONFLICT         = 80
Global Const BTRV_ERR_LOCK             = 81
Global Const BTRV_ERR_LOST_POS         = 82
Global Const BTRV_ERR_READ_TRANS       = 83
Global Const BTRV_ERR_REC_LOCKED       = 84
Global Const BTRV_ERR_FILE_LOCKED      = 85
Global Const BTRV_ERR_FILE_TBL_FULL    = 86
Global Const BTRV_ERR_HNDL_TBL_FULL    = 87
Global Const BTRV_ERR_INCOM_MODE       = 88
Global Const BTRV_ERR_REDIR_DEV_FULL   = 90
Global Const BTRV_ERR_SERVER           = 91
Global Const BTRV_ERR_TRANS_TBL_FULL   = 92
Global Const BTRV_ERR_INCOM_LOCK       = 93
Global Const BTRV_ERR_PERMISSION       = 94
Global Const BTRV_ERR_SESSION          = 95
Global Const BTRV_ERR_COMM_ENV         = 96
Global Const BTRV_ERR_DATA_MSGSIZE     = 97
Global Const BTRV_ERR_INTERNAL_TRANS   = 98

' Data conversion errors.

' Control errors
